language: python
python:
  - "3.8"
services:
  - "docker"

install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
script:
  - "pylint --load-plugins pylint_quotes scan.py"
  - "docker build -t minecraft-scan ."
