apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: minecraft-scan
  name: minecraft-scan
  namespace: minecraft-scan
spec:
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  source:
    git:
      uri: "https://github.com/mxmeinhold/minecraft-scan.git"
  output:
    to:
      kind: ImageStreamTag
      name: minecraft-scan:latest
  runPolicy: Serial
  strategy:
    dockerStrategy: {}
    type: Docker
